spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

uaa:
  clientId: analytics_client
  clientSecret: secret
  clientBase64Token: YW5hbHl0aWNzX2NsaWVudDpzZWNyZXQ=
  uri: https://bc59f9ee-7a17-4d01-879d-f9d471f2696c.predix-uaa.run.aws-usw02-pr.ice.predix.io

gatewayAPI:
  uri: https://predix-geo-gateway.run.aws-usw02-pr.ice.predix.io

scheduler:
  time: 1000
---
spring:
  profiles: cloud

uaa:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  clientBase64Token: ${CLIENT_BASE64_TOKEN}
  uri: ${UAA_URI}

gatewayAPI:
  uri: ${GATEWAY_URI}

scheduler:
  time: ${SCHEDULER_TIME}